image: docker:19.03

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03-dind

stages:
  - build

build_docker:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add git make bash go file
  script:
    - make push
